# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anagramma.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameOne(object):
    def setupUi(self, GameOne):
        GameOne.setObjectName("GameOne")
        GameOne.resize(776, 610)
        self.centralwidget = QtWidgets.QWidget(GameOne)
        self.centralwidget.setObjectName("centralwidget")
        self.word = QtWidgets.QLabel(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(180, 40, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(22)
        self.word.setFont(font)
        self.word.setFocusPolicy(QtCore.Qt.NoFocus)
        self.word.setObjectName("word")
        self.answord = QtWidgets.QLineEdit(self.centralwidget)
        self.answord.setGeometry(QtCore.QRect(110, 220, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.answord.setFont(font)
        self.answord.setText("")
        self.answord.setObjectName("answord")
        self.corrnum = QtWidgets.QLCDNumber(self.centralwidget)
        self.corrnum.setGeometry(QtCore.QRect(140, 420, 111, 71))
        self.corrnum.setObjectName("corrnum")
        self.ansbtn = QtWidgets.QPushButton(self.centralwidget)
        self.ansbtn.setGeometry(QtCore.QRect(490, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.ansbtn.setFont(font)
        self.ansbtn.setObjectName("ansbtn")
        self.corrword = QtWidgets.QLabel(self.centralwidget)
        self.corrword.setGeometry(QtCore.QRect(40, 410, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(17)
        self.corrword.setFont(font)
        self.corrword.setObjectName("corrword")
        self.timeword = QtWidgets.QLabel(self.centralwidget)
        self.timeword.setGeometry(QtCore.QRect(350, 410, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(14)
        self.timeword.setFont(font)
        self.timeword.setObjectName("timeword")
        self.timenum = QtWidgets.QLCDNumber(self.centralwidget)
        self.timenum.setGeometry(QtCore.QRect(550, 430, 151, 51))
        self.timenum.setObjectName("timenum")
        GameOne.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GameOne)
        self.statusbar.setObjectName("statusbar")
        GameOne.setStatusBar(self.statusbar)

        self.retranslateUi(GameOne)
        QtCore.QMetaObject.connectSlotsByName(GameOne)

    def retranslateUi(self, GameOne):
        _translate = QtCore.QCoreApplication.translate
        GameOne.setWindowTitle(_translate("GameOne", "MainWindow"))
        self.word.setText(_translate("GameOne", "                    Text"))
        self.ansbtn.setText(_translate("GameOne", "OK"))
        self.corrword.setText(_translate("GameOne", "Верно"))
        self.timeword.setText(_translate("GameOne", "Осталось времени"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameOne = QtWidgets.QMainWindow()
    ui = Ui_GameOne()
    ui.setupUi(GameOne)
    GameOne.show()
    sys.exit(app.exec_())
