# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_Database(object):
    def setupUi(self, Database):
        Database.setObjectName("Database")
        self.con = sqlite3.connect("stat.db")
        self.con.open()

        Database.resize(803, 662)
        self.tableWidget = QtWidgets.QTableWidget(Database)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 761, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(Database)
        self.label.setGeometry(QtCore.QRect(290, 30, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")


        self.retranslateUi(Database)
        QtCore.QMetaObject.connectSlotsByName(Database)

    def retranslateUi(self, Database):
        _translate = QtCore.QCoreApplication.translate
        Database.setWindowTitle(_translate("Database", "Form"))
        self.label.setText(_translate("Database", "Ваши результаты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Database = QtWidgets.QWidget()
    ui = Ui_Database()
    ui.setupUi(Database)
    Database.show()
    sys.exit(app.exec_())
