# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogwid.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lang(object):
    def setupUi(self, Lang):
        Lang.setObjectName("Lang")
        Lang.resize(525, 185)
        self.label = QtWidgets.QLabel(Lang)
        self.label.setGeometry(QtCore.QRect(90, 40, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Lang)
        self.pushButton.setGeometry(QtCore.QRect(180, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(Lang)
        self.radioButton.setGeometry(QtCore.QRect(210, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Lang)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 70, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Lang)
        QtCore.QMetaObject.connectSlotsByName(Lang)

    def retranslateUi(self, Lang):
        _translate = QtCore.QCoreApplication.translate
        Lang.setWindowTitle(_translate("Lang", "Form"))
        self.label.setText(_translate("Lang", "Язык"))
        self.pushButton.setText(_translate("Lang", "OK"))
        self.radioButton.setText(_translate("Lang", "Русский язык"))
        self.radioButton_2.setText(_translate("Lang", "Башкорт тель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lang = QtWidgets.QWidget()
    ui = Ui_Lang()
    ui.setupUi(Lang)
    Lang.show()
    sys.exit(app.exec_())
