# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 614)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 60, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startbtn = QtWidgets.QPushButton(self.centralwidget)
        self.startbtn.setGeometry(QtCore.QRect(310, 200, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.startbtn.setFont(font)
        self.startbtn.setObjectName("startbtn")
        self.staticbtn = QtWidgets.QPushButton(self.centralwidget)
        self.staticbtn.setGeometry(QtCore.QRect(310, 300, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.staticbtn.setFont(font)
        self.staticbtn.setObjectName("staticbtn")
        self.settingsbtn = QtWidgets.QPushButton(self.centralwidget)
        self.settingsbtn.setGeometry(QtCore.QRect(310, 410, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.settingsbtn.setFont(font)
        self.settingsbtn.setObjectName("settingsbtn")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тренировка внимания"))
        self.startbtn.setText(_translate("MainWindow", "Начать"))
        self.staticbtn.setText(_translate("MainWindow", "Статистика"))
        self.settingsbtn.setText(_translate("MainWindow", "Настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
