# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordcheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pass(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timenum = QtWidgets.QLCDNumber(self.centralwidget)
        self.timenum.setGeometry(QtCore.QRect(590, 460, 151, 51))
        self.timenum.setObjectName("timenum")
        self.corrword = QtWidgets.QLabel(self.centralwidget)
        self.corrword.setGeometry(QtCore.QRect(80, 440, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(17)
        self.corrword.setFont(font)
        self.corrword.setObjectName("corrword")
        self.corrnum = QtWidgets.QLCDNumber(self.centralwidget)
        self.corrnum.setGeometry(QtCore.QRect(180, 450, 111, 71))
        self.corrnum.setObjectName("corrnum")
        self.answord = QtWidgets.QLineEdit(self.centralwidget)
        self.answord.setGeometry(QtCore.QRect(150, 250, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.answord.setFont(font)
        self.answord.setText("")
        self.answord.setObjectName("answord")
        self.ansbtn = QtWidgets.QPushButton(self.centralwidget)
        self.ansbtn.setGeometry(QtCore.QRect(530, 250, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.ansbtn.setFont(font)
        self.ansbtn.setObjectName("ansbtn")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(220, 70, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(22)
        self.password.setFont(font)
        self.password.setFocusPolicy(QtCore.Qt.NoFocus)
        self.password.setObjectName("password")
        self.timeword = QtWidgets.QLabel(self.centralwidget)
        self.timeword.setGeometry(QtCore.QRect(390, 440, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(14)
        self.timeword.setFont(font)
        self.timeword.setObjectName("timeword")
        self.word_2 = QtWidgets.QLabel(self.centralwidget)
        self.word_2.setGeometry(QtCore.QRect(310, -10, 191, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(22)
        self.word_2.setFont(font)
        self.word_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.word_2.setObjectName("word_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.corrword.setText(_translate("MainWindow", "Верно"))
        self.ansbtn.setText(_translate("MainWindow", "OK"))
        self.password.setText(_translate("MainWindow", "                    Text"))
        self.timeword.setText(_translate("MainWindow", "Затрачено времени"))
        self.word_2.setText(_translate("MainWindow", "Ваш пароль:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Pass()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
